platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0'
end

target 'LightSwitch' do
  shared_pods
end

target 'LightSwitchTests' do
  shared_pods
  pod 'RxBlocking'
  pod 'RxTest'
  pod 'Sourcery'
  pod 'Quick'
  pod 'RxNimble', subspecs: ['RxBlocking', 'RxTest']
end
